In [1]:
import numpy as np
from scipy import spatial
def distance_metrics(gt, preds):
    errors = np.zeros(gt.shape[:-1])

    for i in range(errors.shape[0]):
        for j in range(errors.shape[1]):
            errors[i, j] = spatial.distance.euclidean(gt[i, j], preds[i, j])
    return errors.mean(), errors[:, -1].mean(), errors

In [2]:
gt = np.load("gt.npy")
pr = np.load("pr.npy")

In [3]:
pr.shape

(453, 12, 2)

In [4]:
pr[0]

array([[ 722.4613 ,  965.9904 ],
       [ 776.13367, 1463.956  ],
       [ 828.45514, 1970.9204 ],
       [ 880.4758 , 2482.3345 ],
       [ 932.46545, 2996.78   ],
       [ 984.5203 , 3513.6833 ],
       [1036.6637 , 4032.2764 ],
       [1088.8835 , 4551.402  ],
       [1141.1608 , 5069.8906 ],
       [1193.4752 , 5587.1353 ],
       [1245.811  , 6103.399  ],
       [1298.168  , 6619.563  ]], dtype=float32)

In [6]:
gt[0]

array([[646.5135, 486.1675],
       [641.2625, 491.468 ],
       [613.9385, 488.8855],
       [593.0585, 488.8275],
       [591.6685, 488.867 ],
       [612.5685, 467.956 ],
       [609.991 , 483.5745],
       [590.4215, 509.6775],
       [576.1635, 509.613 ],
       [561.793 , 511.0265],
       [530.4155, 492.748 ],
       [503.129 , 512.2875]], dtype=float32)

In [9]:
mad, fad, errs = distance_metrics(gt, pr)

In [13]:
errs

array([[  485.7963562 ,   981.79589844,  1497.47949219, ...,
         5115.26171875,  5656.07568359,  6158.80664062],
       [  457.22381592,   945.09729004,  1431.31933594, ...,
         4890.37304688,  5388.56640625,  5893.06787109],
       [  909.46362305,  1800.53100586,  2682.97265625, ...,
         8844.94433594,  9721.73242188, 10577.42285156],
       ...,
       [  506.41168213,  1072.64526367,  1648.99267578, ...,
         5763.41748047,  6334.21582031,  6895.34375   ],
       [  737.90405273,  1448.33789062,  2175.23901367, ...,
         7232.11181641,  7953.62402344,  8680.29003906],
       [  530.86157227,  1096.34313965,  1644.92553711, ...,
         5513.43847656,  6105.80517578,  6683.578125  ]])